apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-quay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-quay
  template:
    metadata:
      labels:
        app: hello-quay
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%    
      containers:
      - name: hello-quay
        image: quay.io/redhattraining/do480-hello-app:latest
