apiVersion: v1
kind: Namespace
metadata:
  name: etherpad-stage
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etherpad-stage
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - chart: etherpad
      repoURL: https://mmwillingham.github.io/sampleapps
      targetRevision: 0.0.25
      helm:
        valueFiles:
        - $values/gitops_apps/etherpad/values-stage.yaml
    # Values from Git
    - repoURL: 'https://github.com/mmwillingham/sampleapps'
      targetRevision: HEAD
      ref: values        
  destination:    
    server: https://kubernetes.default.svc
    namespace: etherpad-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
      - /status
