resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-k-staging
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8081
    target:
      kind: Service

  - patch: |-
      - op: replace
        path: /spec/port/targetPort
        value: 8081
    target:
      kind: Route

images:
- name: quay.io/redhattraining/do480-hello-app
  newTag: latest