apiVersion: v1
kind: Namespace
metadata:
  name: etherpad-umbrella-green
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etherpad-umbrella-green
  namespace: openshift-gitops
spec:
  destination:
    namespace: etherpad-umbrella-green
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops_apps/etherpad-umbrella
    repoURL: https://github.com/mmwillingham/sampleapps/gitops_apps/etherpad-umbrella
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-green.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
      - /status
---
