kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: swagger
  labels:
    app: swagger-openshift
    owner: mmw
spec:  
  path: /swagger
  to:
    kind: Service
    name: swagger-service
    weight: 100
  port:
    targetPort: swagger
  wildcardPolicy: None