apiVersion: v1
kind: Service
metadata:
  name: swagger-service  
  labels:
    app: swagger-openshift
    owner: mmw
spec:
  type: ClusterIP
  selector:
    app: swagger-openshift
  ports:
  - name: swagger
    protocol: TCP
    port: 9080
    targetPort: 8080