apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    name: kind
  project: default
  source:
    path: helm-umbrella-chart
    repoURL: https://github.com/morey-tech/argo-cd-helm-values-demo
    targetRevision: HEAD
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files
      valueFiles:
      - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true