---
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::519926745982:role/bosez-gdabs-Rosa-s3
  name: test-sa
  namespace: test-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awscli-sts-debug
  annotations:
    openshift.io/scc: anyuid
  name: awscli-sts-debug
  namespace: test-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: awscli-sts-debug
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: awscli-sts-debug
    spec:
      containers:
      - image: amazon/aws-cli:latest
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 10; done"
        imagePullPolicy: Always
        name: aws-cli
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: test-sa
      serviceAccountName: test-sa

