# {{- if .Values.route.enabled -}}
# {{- $fullName := include "etherpad.fullname" . -}}
# {{- $svcPort := .Values.service.port -}}
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   annotations:
#     openshift.io/host.generated: "true"
#   name: {{ $fullName }}

#   labels:
#     {{- include "etherpad.labels" . | nindent 4 }}
# spec:
#   host: {{ .Values.route.host | quote }}
#   port:
#     targetPort: {{ .Values.route.targetPort | default "8080-tcp" }}
#   to:
#     kind: Service
#     name: {{ $fullName }}
#     weight: 100
#   tls:
#     insecureEdgeTerminationPolicy: Redirect
#     termination: edge
# status:
#   ingress:
#       conditions:
#         - status: 'True'
#           type: Admitted
# {{ end }}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: etherpad-prod
  namespace: etherpad-prod
  labels:
    app.kubernetes.io/instance: etherpad-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etherpad
    app.kubernetes.io/version: latest
    helm.sh/chart: etherpad-0.0.15
spec:
  to:
    kind: Service
    name: etherpad-prod
  tls: {}
  port:
    targetPort: http