kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-quay
  labels: {}
spec:
  to:
    kind: Service
    name: hello-quay-blue
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge  