apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etherpad-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: etherpad
    repoURL: https://mmwillingham.github.io/sampleapps/
    targetRevision: 0.0.27
    ## override default values in values.yaml
    helm:
      values: |
        replicaCount: "3"
        fullnameOverride: "etherpad-prod"
  destination:    
    server: https://kubernetes.default.svc
    namespace: etherpad-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
      - /status
