kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    haproxy.router.openshift.io/disable_cookies: true
  name: hello-quay
  labels: {}
spec:
  to:
    kind: Service
    name: hello-quay-blue
    weight: 100
  alternateBackends:
    - weight: 0
      kind: Service
      name: hello-quay-green 
  port:
    targetPort: 8080
  tls:
    termination: edge  