resources:
- ../../base
- route.yaml
- service.yaml

namePrefix: prod-

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-k-prod
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2  
    target:
      kind: Deployment


kind: Deployment
metadata:
  name: hello-quay
  labels:
    app: hello-quay
    name: hello-quay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-quay
      name: hello-quay
  template:
    metadata:
      labels:
        app: hello-quay
        name: hello-quay
    spec:
      containers:
      - name: hello-quay
        image: quay.io/redhattraining/do480-hello-app:v1.0


  # - patch: |-
  #     - op: replace
  #       path: /spec/ports/0/port
  #       value: 8082
  #   target:
  #     kind: Service

  # - patch: |-
  #     - op: replace
  #       path: /spec/port/targetPort
  #       value: 8082
  #   target:
  #     kind: Route
