resources:
- ../../base
commonLabels:
  app: hello-world-kustomize-prod

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-k-prod
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment

  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: hello-quay
      spec:
        ports:
        - port: 8082

  - patch: |-
      apiVersion: apps/v1
      kind: Route
      metadata:
        name: hello-quay      
      spec:
        port:
          targetPort: 8082
        to:
          kind: Service
          name: hello-quay
          weight: 100
        port:
          targetPort: OVERLAY_VALUE

  # - patch: |-
  #     - op: replace
  #       path: /spec/ports/0/port
  #       value: 8082
  #   target:
  #     kind: Service

  # - patch: |-
  #     - op: replace
  #       path: /spec/port/targetPort
  #       value: 8082
  #   target:
  #     kind: Route
