resources:
- ../../base

namePrefix: prod-

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-k-prod
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8082
    target:
      kind: Service

  - patch: |-
      - op: replace
        path: /spec/port/targetPort
        value: 8082
      - op: replace
        path: /spec/to/name
        value: prod-hello-quay
    target:
      kind: Route

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2  
    target:
      kind: Deployment