resources:
- ../../base

images:
- name: quay.io/redhattraining/do480-hello-app
  newTag: latest  # GREEN HAS latest TAG

commonLabels:
  app: hello-quay-green

patches:

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-green
      - op: replace
        path: /spec/replicas
        value: 1                                # GREEN HAS 2 REPLICAS
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-green
    target:
      kind: Service   