apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: master-app-etherpad-stage
  namespace: openshift-gitops
  labels:
    appgrp: day2
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: gitops_apps/etherpad/stage
    repoURL: https://github.com/mmwillingham/sampleapps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true