resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-bg-blue
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-blue
      - op: replace
        path: /spec/replicas
        value: 2                                # BLUE HAS 2 REPLICAS
      - op: replace
        path: /spec/selector/matchLabels/0/app
        value: hello-quay-blue
      - op: replace
        path: /spec/template/metadata/labels/app
        value: hello-quay-blue
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/redhattraining/do480-hello-app:v1.0     # BLUE HAS v1.0 TAG
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-blue
      - op: replace
        path: /spec/selector/matchLabels/0/app
        value: hello-quay-blue
    target:
      kind: Service      
