resources:
- ../../base

images:
- name: quay.io/redhattraining/do480-hello-app
  newTag: latest # BLUE HAS v1.0 TAG


patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-bg-blue
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-blue
      - op: replace
        path: /spec/replicas
        value: 2                                # BLUE HAS 2 REPLICAS
      - op: add
        path: /spec/selector/matchLabels/app
        value: hello-quay-blue
      - op: replace
        path: /spec/selector/matchLabels/app
        value: hello-quay-blue
      - op: replace
        path: /spec/template/metadata/labels/app
        value: hello-quay-blue
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-blue
      - op: replace
        path: /spec/selector/matchLabels/0/app
        value: hello-quay-blue
    target:
      kind: Service

?
