resources:
- ../../base

images:
- name: quay.io/redhattraining/do480-hello-app
  newTag: v1.0    # BLUE HAS V1.0 TAG

commonLabels:
  app: hello-quay-blue

patches:

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-blue
      - op: replace
        path: /spec/replicas
        value: 2                                # BLUE HAS 2 REPLICAS
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-blue
    target:
      kind: Service   