apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 3
  minReadySeconds: 30
  progressDeadlineSeconds: 60
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hello-quay
  template:
    metadata:
      labels:
        app: hello-quay
    spec:
      containers:
      - name: hello-quay
        #image: quay.io/redhattraining/do480-hello-app:v1.0
        image: {{ .Values.image }}:{{ .Values.imagetag }}
        #image: quay.io/redhattraining/do480-hello-app:NOT_A_VERSION