resources:
- ../../base

images:
- name: quay.io/redhattraining/do480-hello-app
  newTag: v1.0  # GREEN HAS V1.0 TAG

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-world-bg-green
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-green
      - op: replace
        path: /spec/replicas
        value: 1                               # GREEN HAS 1 REPLICA
      - op: replace
        path: /spec/selector/matchLabels/0/app
        value: hello-quay-green
      - op: replace
        path: /spec/template/labels/0/app
        value: hello-quay-green
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hello-quay-green
      - op: replace
        path: /spec/selector/matchLabels/0/app
        value: hello-quay-green
    target:
      kind: Service   